<?xml version="1.0"?>
<package format="3">
  <name>s2m_bringup</name>
  <version>1.1.0</version>
  <description>Scout2Map UGV Gazebo, SLAM Toolbox and Nav2 integration bringup</description>
  <maintainer email="Scout2Map@users.noreply.github.com">Scout2Map</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>s2m_description</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>action_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>scout2map_msgs</exec_depend>
  <exec_depend>scout2map_bridge</exec_depend>
  <exec_depend>scout2map_event</exec_depend>
  <exec_depend>scout_vision</exec_depend>
  <exec_depend>scout2map_comm</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>sllidar_ros2</exec_depend>
  <exec_depend>explore_lite</exec_depend>
  <test_depend>ament_cmake_pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
